version: "{build}"
build: off
shallow_clone: true
skip_tags: true

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "16"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm i

test_script:
  - npm test
